include: package:xsoulspace_lints/library.yaml

analyzer:
  enable-experiment:
    - inline-class
  exclude:
    - bin/cache/*
    # Please do not change this to lib wide
    # rule, since the app_router.gr.dart can often
    # be cause of missing dependencies.
    - lib/**.*.dart

  errors:
    unused_local_variable: info
    require_trailing_commas: error
    flutter_style_todos: error
linter:
  rules:
    avoid_annotating_with_dynamic: false
