name: tg_la_bot
description: A pure client-side app without ssr.
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  jaspr: ^0.10.0
  televerse: ^1.13.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  jaspr_builder: ^0.10.0
  jaspr_web_compilers: ^4.0.7+1
  xsoulspace_lints: ^0.0.10

jaspr:
  uses-ssr: false
