type: server

client_package_path: ../core_server_client

modules:
  serverpod_auth:
    nickname: auth
extraClasses:
  - package:shared_models/shared_models.dart:RemoteUserModel
  - package:shared_models/shared_models.dart:PurchaseActionModel
