name: core_server_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  serverpod: ^1.1.1
  serverpod_auth_server: ^1.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  xsoulspace_lints: ^0.0.10
