name: landing
description: A pure client-side app without ssr.
version: 0.0.1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  jaspr: ^0.15.1
  jaspr_router: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.11
  collection: ^1.19.0
  jaspr_builder: ^0.15.1
  lints: ^4.0.0

jaspr:
  mode: client
