name: landing
description: A pure client-side app without ssr.
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  jaspr: ^0.10.0

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.7+1
  jaspr_builder: ^0.10.0
  lints: ^2.1.0

jaspr:
  uses-ssr: false
