name: landing
description: A pure client-side app without ssr.
version: 0.0.1

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  jaspr: ^0.17.0
  jaspr_router: ^0.6.1

dev_dependencies:
  build_runner: ^2.4.14
  collection: ^1.19.1
  jaspr_builder: ^0.17.0
  jaspr_web_compilers: ^4.1.0
  lints: ^5.1.1

jaspr:
  mode: client
