include: package:xsoulspace_lints/app.yaml

analyzer:
  enable-experiment:
    - inline-class
  exclude:
    - lib/**.*.dart
    - lib/l10n/l10n.dart
    - lib/l10n/l10n_*.dart

  errors:
    unused_local_variable: info
    require_trailing_commas: error
    flutter_style_todos: error
linter:
  rules:
    avoid_annotating_with_dynamic: false
