name: lastanswer
description: Fast ideas brainstroming tool

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.5.2+7

environment:
  sdk: ">=2.14.0 <3.0.0"

# to update use flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.7
  json_annotation: ^4.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  # To build use flutter pub run build_runner build
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  universal_io: ^2.0.4
  share_plus: ^3.0.4
  uuid: ^3.0.4
  flutter_hooks: ^0.18.0
  flutter_riverpod: ^1.0.0-dev.7
  hooks_riverpod: ^1.0.0-dev.7
  riverpod: ^1.0.0-dev.7
  equatable: ^2.0.3
  google_fonts: ^2.1.0
  flutter_svg: ^0.23.0+1
  flare_flutter: ^3.0.2
  collection: ^1.15.0
  quiver: ^3.0.0
  path_to_regexp: ^0.4.0
  package_info_plus: ^1.3.0
  recase: ^4.0.0
  rxdart: ^0.27.2
  flutter_portal: ^0.4.0
  blur: ^3.0.0
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.2
  flutter_lints: ^1.0.4
  flutter_gen: ^4.0.0
  flutter_gen_runner: ^4.0.0
  mocktail: ^0.2.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/promo/icon-512-green.png"
  ios: true
  android: true
  remove_alpha_ios: true

# For information see the following page:
# https://pub.dev/packages/flutter_gen
flutter_gen:
  # output: lib/gen/ # Optional (default: lib/gen/)
  # line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - google_fonts/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: google_fonts/IBMPlexSans-Thin.ttf
          weight: 100
        - asset: google_fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: google_fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: google_fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: google_fonts/IBMPlexSans-SemiBold.ttf
          weight: 700
        - asset: google_fonts/IBMPlexSans-Bold.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
