arb-dir: lib/src/l10n
template-arb-file: intl_en.arb
output-dir: lib/src/gen/l10n
output-localization-file: S.dart
output-class: S
synthetic-package: false
nullable-getter: false
untranslated-messages-file: lib/src/gen/untraslated_strings.txt
