name: ui_kit
description: Unified ui layer & its tools
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: ">=3.24.2"

dependencies:
  collection: ^1.19.0
  connectivity_plus: ^6.0.5
  core:
    path: ../core
  equatable: ^2.0.5
  firebase_analytics: ^11.3.3
  firebase_analytics_web: ^0.5.10+2
  firebase_core: ^3.6.0
  firebase_core_web: ^2.18.1
  firebase_crashlytics: ^4.1.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  form_builder_validators: ^11.0.0
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  share_plus: ^10.0.2
  shared_models:
    path: ../shared_models
  shared_preferences: ^2.3.2
  universal_io: ^2.2.2
  url_launcher: ^6.3.0
  uuid: ^4.5.1

dependency_overrides:
  collection: ^1.19.0
  connectivity_plus: ^6.0.5
  flutter_lints: ^5.0.0
  http: ^1.2.2
  intl: ^0.19.0
  lints: ^5.0.0
  meta: ^1.16.0
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  faker: ^2.2.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  # isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  xsoulspace_lints: ^0.0.10
