name: ui_kit
description: Unified ui layer & its tools
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  core:
    path: ../core
  equatable: ^2.0.5
  firebase_analytics: ^10.6.1
  firebase_core: ^2.19.0
  firebase_crashlytics: ^3.4.6
  firebase_messaging: ^14.7.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  package_info_plus: ^4.2.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  shared_models:
    path: ../shared_models
  shared_preferences: ^2.2.2
  universal_io: ^2.2.2
  url_launcher: ^6.1.14
  uuid: ^4.1.0

dependency_overrides:
  analyzer: ^6.3.0
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  flutter_lints: ^3.0.0
  http: ^1.1.2
  lints: ^3.0.0
  intl: ^0.18.1
  meta: ^1.11.0
  uuid: ^4.1.0

dev_dependencies:
  analyzer: ^6.3.0
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  faker: ^2.1.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  # isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  mocktail: ^1.0.1
  mocktail_image_network: ^1.0.0
  xsoulspace_lints: ^0.0.10
