name: ui_kit
description: Unified ui layer & its tools
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  collection: ^1.19.1
  connectivity_plus: ^6.1.2
  core:
  equatable: ^2.0.7
  firebase_analytics: ^11.4.0
  firebase_analytics_web: ^0.5.10+6
  firebase_core: ^3.10.0
  firebase_core_web: ^2.19.0
  firebase_crashlytics: ^4.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.0.0
  form_builder_validators: ^11.1.1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.20.1
  json_annotation: ^4.9.0
  logger: ^2.5.0
  package_info_plus: ^8.1.3
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  share_plus: ^10.1.4
  shared_models:
  shared_preferences: ^2.3.5
  universal_io: ^2.2.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  faker: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  injectable_generator: ^2.7.0
  # isar_generator: ^3.1.0+1
  json_serializable: ^6.9.3
  lints: ^5.1.1
  mockito: ^5.4.5
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  xsoulspace_lints: ^0.0.13
