name: ui_kit
description: design ui kit
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.4
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  google_fonts: ^4.0.3
  sliver_tools: ^0.2.9
  tap_builder: ^0.4.1
  ui_locale:
    path: ../ui_locale

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  xsoulspace_lints: ^0.0.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # assets:
  #   - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/json/
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    # - family: la_icons
    #   fonts:
    #     - asset: packages/ui_kit/fonts/la_icons.ttf
    - family: IBMPlexSans
      fonts:
        - asset: packages/ui_kit/fonts/IBMPlexSans-Thin.ttf
          weight: 100
        - asset: packages/ui_kit/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: packages/ui_kit/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: packages/ui_kit/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: packages/ui_kit/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: packages/ui_kit/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: packages/ui_kit/fonts/IBMPlexSans-Bold.ttf
          weight: 700

    # NotoColorEmoji and NotoSans are fallback fonts used to display emojis
    - family: NotoSans
      fonts:
        - asset: packages/ui_kit/fonts/NotoSans-Thin.ttf
          weight: 100
        - asset: packages/ui_kit/fonts/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: packages/ui_kit/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: packages/ui_kit/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: packages/ui_kit/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: packages/ui_kit/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: packages/ui_kit/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: packages/ui_kit/fonts/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: packages/ui_kit/fonts/NotoSans-Black.ttf
          weight: 900

    - family: NotoColorEmoji
      fonts:
        - asset: packages/ui_kit/fonts/NotoColorEmoji.ttf

# For information see the following page:
# https://pub.dev/packages/flutter_gen
flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  # line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
