// Generated by `oka init --from-yaml` (ADR-0010).
//
// Typed, programmable project config: oka.yaml is no longer
// required. Precedence: defaults < oka.yaml (if kept) < this
// file < CLI args (--release/--abi/--dart-define/...).
// Project: lastanswer 3.22.0+51 (from oka.yaml)
import 'package:oka_android/oka_android.dart';
import 'package:oka_core/oka_core.dart';

Future<void> main(List<String> args) => okaRun(
  args,
  oka: Oka(
    pipelines: [
      AndroidPipeline(
        config: AndroidBuild(
          name: 'lastanswer',
          packageName: 'dev.xsoulspace.lastanswer',
          compileSdk: '36',
          targetSdk: '36',
          minSdk: '25',
          versionCode: 51,
          versionName: '3.22.0',
          javaVersion: 17,
        ),
        flutterConfig: FlutterBuild(
          entrypoint: 'lib/main_prod.dart',
        ),
        overrides: PipelineOverrides(
          resDirs: ['android/app/src/main/res'],
          resourceConfigs: ['en', 'ru'],
          excludePlugins: ['integration_test'],
          manifest: const ManifestSpec(permissions: ['android.permission.INTERNET', 'android.permission.ACCESS_NETWORK_STATE', 'android.permission.CAMERA'], cleartextTraffic: true, flutterDeeplinking: true, applicationAttributes: const {'android:icon': '@mipmap/ic_launcher', 'android:label': 'Last Answer'}, activityAttributes: const {'android:theme': '@style/LaunchTheme'}, applicationMetaData: [MetaDataSpec(name: 'io.flutter.embedding.android.NormalTheme', resource: '@style/NormalTheme')], deeplinks: [DeeplinkConfig(scheme: 'https', host: 'xsoulspace.dev', pathPrefix: ''), DeeplinkConfig(scheme: 'http', host: 'xsoulspace.dev', pathPrefix: ''), DeeplinkConfig(scheme: 'dev.xsoulspace.lastanswer', host: '', pathPrefix: '')]),
        ),
        steps: [...AndroidPipeline.defaultSteps],
      ),
    ],
  ),
);
