name: core
description: Unified data layer & tools
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  collection: ^1.19.1
  connectivity_plus: ^6.1.2
  core_server_client:
  equatable: ^2.0.7
  file_picker: ^8.1.7
  file_saver: ^0.2.14
  file_selector: ^1.0.3
  firebase_analytics: ^11.4.0
  firebase_analytics_web: ^0.5.10+6
  firebase_core: ^3.10.0
  firebase_core_web: ^2.19.0
  firebase_crashlytics: ^4.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.0.0
  flutter_inapp_purchase: ^5.6.1
  flutter_quill: ^10.8.5
  form_builder_validators: ^11.1.1
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_purchase: ^3.2.0
  infinite_scroll_pagination: ^4.1.0
  internet_connection_checker: ^3.0.1
  intl: ^0.20.1
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.9.0
  logger: ^2.5.0
  murmur3: ^2.1.0
  package_info_plus: ^8.1.3
  path: ^1.9.1
  path_provider: ^2.1.5
  path_to_regexp: ^0.4.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  quiver: ^3.2.2
  rxdart: ^0.28.0
  serverpod_auth_google_flutter: 2.3.1
  serverpod_auth_shared_flutter: 2.3.1
  serverpod_client: 2.3.1
  serverpod_flutter: 2.3.1
  share_plus: ^10.1.4
  shared_models:
  shared_preferences: ^2.3.5
  televerse: ^2.2.0
  ui_kit:
  universal_io: ^2.2.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  # web: 0.5.0
  yandex_mobileads: ^7.7.0

dependency_overrides:
  intl: ^0.20.1
  meta: ^1.16.0

dev_dependencies:
  analyzer: ^7.2.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  faker: ^2.2.0
  flutter_gen: ^5.8.0
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  hive_generator: ^2.0.1
  injectable_generator: ^2.7.0
  # isar_generator: ^3.1.0+1
  json_serializable: ^6.9.3
  lints: ^5.1.1
  mockito: ^5.4.5
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  xsoulspace_lints: ^0.0.13

# For information see the following page:
# https://pub.dev/packages/flutter_gen
flutter_gen:
  output: lib/src/generated/ # Optional (default: lib/gen/)
  lineLength: 80

  assets:
    enabled: true
    outputs:
      gen_for_package: true
      package_parameter_enabled: true

  integrations:
    flutter_svg: true

  fonts:
    enabled: true

flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/json/
    - google_fonts/

fonts:
  - family: IBMPlexSans
    fonts:
      - asset: google_fonts/IBMPlexSans-Thin.ttf
        weight: 100
      - asset: google_fonts/IBMPlexSans-Light.ttf
        weight: 300
      - asset: google_fonts/IBMPlexSans-Regular.ttf
        weight: 400
      - asset: google_fonts/IBMPlexSans-Medium.ttf
        weight: 500
      - asset: google_fonts/IBMPlexSans-SemiBold.ttf
        weight: 700
      - asset: google_fonts/IBMPlexSans-Bold.ttf
        weight: 900
  - family: NotoColorEmoji
    fonts:
      - asset: google_fonts/NotoColorEmoji.ttf
  - family: NotoSans
    fonts:
      - asset: google_fonts/NotoSans-Regular.ttf
flutter_intl:
  enabled: true
