name: core
description: Unified data layer & tools
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: ">=3.24.2"

dependencies:
  collection: ^1.19.0
  connectivity_plus: ^6.0.5
  core_server_client:
    path: ../core_server_client
  equatable: ^2.0.5
  file_picker: ^8.1.2
  file_saver: ^0.2.14
  file_selector: ^1.0.3
  firebase_analytics: ^11.3.3
  firebase_analytics_web: ^0.5.10+2
  firebase_core: ^3.6.0
  firebase_core_web: ^2.18.1
  firebase_crashlytics: ^4.1.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  # flutter_inapp_purchase: ^5.6.0
  flutter_quill: ^10.8.2
  form_builder_validators: ^11.0.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_purchase: ^3.2.0
  infinite_scroll_pagination: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.9.0
  logger: ^2.4.0
  murmur3: ^2.1.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.4
  path_to_regexp: ^0.4.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  quiver: ^3.2.2
  rxdart: ^0.28.0
  serverpod_auth_google_flutter: ^2.1.3
  serverpod_auth_shared_flutter: ^2.1.3
  serverpod_client: ^2.1.3
  serverpod_flutter: ^2.1.3
  share_plus: ^10.0.2
  shared_models:
    path: ../shared_models
  shared_preferences: ^2.3.2
  televerse: ^1.26.4
  ui_kit:
    path: ../ui_kit
  universal_io: ^2.2.2
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  # web: 0.5.0
  yandex_mobileads: ^7.4.0

dependency_overrides:
  collection: ^1.19.0
  connectivity_plus: ^6.0.5
  flutter_lints: ^5.0.0
  http: ^1.2.2
  intl: ^0.19.0
  lints: ^5.0.0
  meta: ^1.16.0
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  faker: ^2.2.0
  flutter_gen: ^5.7.0
  flutter_gen_runner: ^5.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  # isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  xsoulspace_lints: ^0.0.10

# For information see the following page:
# https://pub.dev/packages/flutter_gen
flutter_gen:
  output: lib/src/generated/ # Optional (default: lib/gen/)
  lineLength: 80

  assets:
    enabled: true
    outputs:
      gen_for_package: true
      package_parameter_enabled: true

  integrations:
    flutter_svg: true

  fonts:
    enabled: true

flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/json/
    - google_fonts/

fonts:
  - family: IBMPlexSans
    fonts:
      - asset: google_fonts/IBMPlexSans-Thin.ttf
        weight: 100
      - asset: google_fonts/IBMPlexSans-Light.ttf
        weight: 300
      - asset: google_fonts/IBMPlexSans-Regular.ttf
        weight: 400
      - asset: google_fonts/IBMPlexSans-Medium.ttf
        weight: 500
      - asset: google_fonts/IBMPlexSans-SemiBold.ttf
        weight: 700
      - asset: google_fonts/IBMPlexSans-Bold.ttf
        weight: 900
  - family: NotoColorEmoji
    fonts:
      - asset: google_fonts/NotoColorEmoji.ttf
  - family: NotoSans
    fonts:
      - asset: google_fonts/NotoSans-Regular.ttf
flutter_intl:
  enabled: true
