name: core
description: core to use inside app
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.6.0
  equatable: ^2.0.5
  firebase_analytics: ^10.0.6
  firebase_analytics_web: ^0.5.1+5
  firebase_auth: ^4.5.0
  firebase_core: ^2.3.0
  firebase_core_web: ^2.0.1
  firebase_crashlytics: ^3.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  flutter_keyboard_visibility: ^5.4.0
  flutter_native_splash: ^2.2.8
  flutter_quill: ^7.1.14
  form_builder_validators: ^8.6.1
  freezed_annotation: ^2.2.0
  go_router: ^7.0.0
  json_annotation: ^4.8.0
  life_hooks: ^0.0.18
  logger: ^1.3.0
  path_to_regexp: ^0.4.0
  provider: ^6.0.5
  quiver: ^3.2.1
  shared_preferences: ^2.1.0
  ui_kit:
    path: ../ui_kit
  ui_locale:
    path: ../ui_locale
  universal_io: ^2.2.0
  uuid: ^3.0.7

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.6.1
  xsoulspace_lints: ^0.0.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
# assets:
#   - assets/images/
# fonts:
# - family: asgard_icons
#   fonts:
#     - asset: packages/ui_kit/fonts/asgard_icons.ttf
# - family: Poppins
#   fonts:
#     - asset: packages/ui_kit/fonts/Poppins-Regular.ttf
#       weight: 400
#     - asset: packages/ui_kit/fonts/Poppins-Bold.ttf
#       weight: 700
