name: server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ^3.9.0

dependencies:
  app_store_server_sdk: ^1.2.10
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  serverpod: ^2.9.1
  serverpod_auth_server: ^2.9.1
  shared_models:
    path: ../shared_models

dev_dependencies:
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2

dependency_overrides:
  google_fonts: ^6.3.2
