name: server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  app_store_server_sdk: ^1.2.9
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  serverpod: ^2.1.3
  serverpod_auth_server: ^2.1.3
  shared_models:
    path: ../../packages/shared_models

dev_dependencies:
  flutter_lints: ^5.0.0
  xsoulspace_lints: ^0.0.10

dependency_overrides:
  connectivity_plus: ^6.0.5
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  lints: ^5.0.0
  uuid: ^4.5.1
