name: server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  app_store_server_sdk: ^1.2.9
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  serverpod: ^2.3.1
  serverpod_auth_server: ^2.3.1
  shared_models:

dev_dependencies:
  lints: ^5.1.1
  xsoulspace_lints: ^0.0.13

dependency_overrides:
  connectivity_plus: ^6.1.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  lints: ^5.1.1
  uuid: ^4.5.1
