name: la_core
description: core to use inside app
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0-290.3.beta <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_keyboard_visibility: ^5.4.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  life_hooks: ^0.0.18
  path_to_regexp: ^0.4.0
  provider: ^6.0.5
  quiver: ^3.2.1
  universal_io: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.6.1
  la_test_utils:
    path: ../la_test_utils
  xsoulspace_lints: ^0.0.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # assets:
  #   - assets/images/
  # fonts:
  # - family: asgard_icons
  #   fonts:
  #     - asset: packages/la_design_core/fonts/asgard_icons.ttf
  # - family: Poppins
  #   fonts:
  #     - asset: packages/la_design_core/fonts/Poppins-Regular.ttf
  #       weight: 400
  #     - asset: packages/la_design_core/fonts/Poppins-Bold.ttf
  #       weight: 700
