import 'dart:async';

import 'package:flutter/material.dart';

import 'ai_layout_engine.dart';
import 'ai_layout_models.dart';

/// {@template ai_layout_builder}
/// Flutter widget that builds AI-generated layouts
///
/// Integrates with Flutter's widget system to render layouts
/// generated by the AI layout engine. Supports real-time updates
/// and adaptive layout changes based on context.
/// {@endtemplate}
class AILayoutBuilder extends StatefulWidget {
  /// {@macro ai_layout_builder}
  const AILayoutBuilder({
    required this.context,
    this.config = const AILayoutConfig(),
    this.engine,
    this.onLayoutGenerated,
    this.fallbackBuilder,
    this.loadingBuilder,
    this.errorBuilder,
    super.key,
  });

  /// Context for AI layout generation
  final AILayoutContext context;

  /// Configuration for layout generation
  final AILayoutConfig config;

  /// Optional custom AI engine
  final AILayoutEngine? engine;

  /// Callback when layout is generated
  final ValueChanged<AILayoutResult>? onLayoutGenerated;

  /// Fallback widget builder
  final WidgetBuilder? fallbackBuilder;

  /// Loading state widget builder
  final WidgetBuilder? loadingBuilder;

  /// Error state widget builder
  final Widget Function(BuildContext, Object)? errorBuilder;

  @override
  State<AILayoutBuilder> createState() => _AILayoutBuilderState();
}

class _AILayoutBuilderState extends State<AILayoutBuilder>
    with TickerProviderStateMixin {
  late final AILayoutEngine _engine;
  AILayoutResult? _currentResult;
  var _isGenerating = false;
  Object? _error;

  late AnimationController _fadeController;
  late AnimationController _scaleController;

  @override
  void initState() {
    super.initState();
    _engine = widget.engine ?? const AILayoutEngine();

    _fadeController = AnimationController(
      duration: const Duration(milliseconds: 300),
      vsync: this,
    );

    _scaleController = AnimationController(
      duration: const Duration(milliseconds: 500),
      vsync: this,
    );

    unawaited(_generateLayout());
  }

  @override
  void didUpdateWidget(final AILayoutBuilder oldWidget) {
    super.didUpdateWidget(oldWidget);

    if (widget.context != oldWidget.context ||
        widget.config != oldWidget.config) {
      unawaited(_generateLayout());
    }
  }

  @override
  void dispose() {
    _fadeController.dispose();
    _scaleController.dispose();
    super.dispose();
  }

  Future<void> _generateLayout() async {
    if (_isGenerating) return;

    setState(() {
      _isGenerating = true;
      _error = null;
    });

    try {
      final result = await _engine.generateLayout(widget.context);

      if (mounted) {
        setState(() {
          _currentResult = result;
          _isGenerating = false;
        });

        widget.onLayoutGenerated?.call(result);

        // Animate in the new layout
        _fadeController.forward();
        _scaleController.forward();
      }
    } catch (error) {
      if (mounted) {
        setState(() {
          _error = error;
          _isGenerating = false;
        });
      }
    }
  }

  @override
  Widget build(final BuildContext context) {
    if (_error != null) {
      return widget.errorBuilder?.call(context, _error!) ??
          _buildDefaultError();
    }

    if (_isGenerating || _currentResult == null) {
      return widget.loadingBuilder?.call(context) ?? _buildDefaultLoading();
    }

    return AnimatedBuilder(
      animation: Listenable.merge([_fadeController, _scaleController]),
      builder: (final context, final child) => Opacity(
        opacity: _fadeController.value,
        child: Transform.scale(
          scale: 0.8 + (_scaleController.value * 0.2),
          child: _buildAILayout(_currentResult!),
        ),
      ),
    );
  }

  Widget _buildAILayout(final AILayoutResult result) =>
      AILayoutRenderer(layoutTree: result.layoutTree, config: widget.config);

  Widget _buildDefaultLoading() => const Center(
    child: Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        CircularProgressIndicator(),
        SizedBox(height: 16),
        Text('Generating AI Layout...'),
      ],
    ),
  );

  Widget _buildDefaultError() => Center(
    child: Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        const Icon(Icons.error_outline, size: 48, color: Colors.red),
        const SizedBox(height: 16),
        const Text('Failed to generate layout'),
        const SizedBox(height: 8),
        ElevatedButton(onPressed: _generateLayout, child: const Text('Retry')),
      ],
    ),
  );
}

/// {@template ai_layout_renderer}
/// Renders AI-generated layout tree as Flutter widgets
/// {@endtemplate}
class AILayoutRenderer extends StatelessWidget {
  /// {@macro ai_layout_renderer}
  const AILayoutRenderer({
    required this.layoutTree,
    required this.config,
    super.key,
  });

  /// Layout tree to render
  final LayoutTree layoutTree;

  /// Configuration for rendering
  final AILayoutConfig config;

  @override
  Widget build(final BuildContext context) => Stack(
    children: [
      _buildLayoutNode(layoutTree.rootNode),
      if (config.enableExperimental) _buildDebugOverlay(),
    ],
  );

  Widget _buildLayoutNode(final LayoutNode node) {
    final widget = _createWidgetForNode(node);

    return Positioned(
      left: node.bounds.left,
      top: node.bounds.top,
      width: node.bounds.width,
      height: node.bounds.height,
      child: widget,
    );
  }

  Widget _createWidgetForNode(final LayoutNode node) {
    final baseWidget = _createBaseWidget(node);

    // Apply transformations if specified
    Widget transformedWidget = baseWidget;

    if (node.properties.containsKey('rotation')) {
      final rotation = node.properties['rotation'] as double;
      transformedWidget = Transform.rotate(
        angle: rotation,
        child: transformedWidget,
      );
    }

    if (node.properties.containsKey('scale')) {
      final scale = node.properties['scale'] as double;
      transformedWidget = Transform.scale(
        scale: scale,
        child: transformedWidget,
      );
    }

    // Apply elevation/shadow
    if (node.properties.containsKey('elevation')) {
      final elevation = node.properties['elevation'] as double;
      transformedWidget = Material(
        elevation: elevation,
        borderRadius: _getBorderRadius(node),
        child: transformedWidget,
      );
    }

    return transformedWidget;
  }

  Widget _createBaseWidget(final LayoutNode node) {
    switch (node.type) {
      case LayoutNodeType.container:
        return _buildContainer(node);
      case LayoutNodeType.text:
        return _buildText(node);
      case LayoutNodeType.image:
        return _buildImage(node);
      case LayoutNodeType.button:
        return _buildButton(node);
      case LayoutNodeType.input:
        return _buildInput(node);
      case LayoutNodeType.list:
        return _buildList(node);
      case LayoutNodeType.grid:
        return _buildGrid(node);
      case LayoutNodeType.custom:
        return _buildCustom(node);
    }
  }

  Widget _buildContainer(final LayoutNode node) => Container(
    decoration: BoxDecoration(
      color: _getBackgroundColor(node),
      borderRadius: _getBorderRadius(node),
      border: _getBorder(node),
    ),
    padding: _getPadding(node),
    child: Stack(children: node.children.map(_buildLayoutNode).toList()),
  );

  Widget _buildText(final LayoutNode node) => Container(
    alignment: _getAlignment(node),
    child: Text(
      node.properties['text'] as String? ?? 'Sample Text',
      style: TextStyle(
        fontSize: node.properties['fontSize'] as double? ?? 16,
        color: node.properties['color'] as Color? ?? Colors.black,
        fontWeight:
            node.properties['fontWeight'] as FontWeight? ?? FontWeight.normal,
      ),
      textAlign: _getTextAlign(node),
      maxLines: node.properties['maxLines'] as int?,
      overflow: TextOverflow.ellipsis,
    ),
  );

  Widget _buildImage(final LayoutNode node) => DecoratedBox(
    decoration: BoxDecoration(
      borderRadius: _getBorderRadius(node),
      color: Colors.grey[300],
    ),
    child: ClipRRect(
      borderRadius: _getBorderRadius(node),
      child: node.properties['imageUrl'] != null
          ? Image.network(
              node.properties['imageUrl'] as String,
              fit: BoxFit.cover,
              errorBuilder: (final context, final error, final stackTrace) =>
                  _buildImagePlaceholder(),
            )
          : _buildImagePlaceholder(),
    ),
  );

  Widget _buildImagePlaceholder() => Container(
    color: Colors.grey[300],
    child: const Center(child: Icon(Icons.image, color: Colors.grey)),
  );

  Widget _buildButton(final LayoutNode node) => ElevatedButton(
    onPressed: () {
      // Handle button press
    },
    style: ElevatedButton.styleFrom(
      backgroundColor: _getBackgroundColor(node),
      foregroundColor: node.properties['textColor'] as Color? ?? Colors.white,
      shape: RoundedRectangleBorder(borderRadius: _getBorderRadius(node)),
    ),
    child: Text(
      node.properties['text'] as String? ?? 'Button',
      style: TextStyle(fontSize: node.properties['fontSize'] as double? ?? 16),
    ),
  );

  Widget _buildInput(final LayoutNode node) => TextField(
    decoration: InputDecoration(
      hintText: node.properties['placeholder'] as String? ?? 'Enter text...',
      border: OutlineInputBorder(borderRadius: _getBorderRadius(node)),
      filled: true,
      fillColor: _getBackgroundColor(node),
    ),
  );

  Widget _buildList(final LayoutNode node) => ListView.builder(
    scrollDirection: node.properties['horizontal'] == true
        ? Axis.horizontal
        : Axis.vertical,
    itemCount: node.children.length,
    itemBuilder: (final context, final index) =>
        _buildLayoutNode(node.children[index]),
  );

  Widget _buildGrid(final LayoutNode node) {
    final crossAxisCount = node.properties['crossAxisCount'] as int? ?? 2;

    return GridView.builder(
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: crossAxisCount,
        crossAxisSpacing: 8,
        mainAxisSpacing: 8,
      ),
      itemCount: node.children.length,
      itemBuilder: (final context, final index) =>
          _buildLayoutNode(node.children[index]),
    );
  }

  Widget _buildCustom(final LayoutNode node) => DecoratedBox(
    decoration: BoxDecoration(
      color: Colors.blue[100],
      borderRadius: _getBorderRadius(node),
      border: Border.all(color: Colors.blue),
    ),
    child: const Center(child: Text('Custom Widget')),
  );

  Widget _buildDebugOverlay() => Positioned(
    top: 16,
    right: 16,
    child: Container(
      padding: const EdgeInsets.all(8),
      decoration: BoxDecoration(
        color: Colors.black54,
        borderRadius: BorderRadius.circular(8),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          const Text(
            'AI Layout Debug',
            style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
          ),
          Text(
            'Nodes: ${_countNodes(layoutTree.rootNode)}',
            style: const TextStyle(color: Colors.white70),
          ),
          Text(
            'Generated: ${layoutTree.metadata.generatedAt.toString().substring(11, 19)}',
            style: const TextStyle(color: Colors.white70),
          ),
        ],
      ),
    ),
  );

  int _countNodes(final LayoutNode node) =>
      1 +
      node.children.fold(
        0,
        (final sum, final child) => sum + _countNodes(child),
      );

  // Helper methods for property extraction
  Color? _getBackgroundColor(final LayoutNode node) =>
      node.properties['backgroundColor'] as Color?;

  BorderRadius _getBorderRadius(final LayoutNode node) {
    final radius = node.properties['borderRadius'] as double? ?? 0;
    return BorderRadius.circular(radius);
  }

  Border? _getBorder(final LayoutNode node) {
    final borderColor = node.properties['borderColor'] as Color?;
    final borderWidth = node.properties['borderWidth'] as double? ?? 1;

    if (borderColor != null) {
      return Border.all(color: borderColor, width: borderWidth);
    }
    return null;
  }

  EdgeInsets _getPadding(final LayoutNode node) {
    final padding = node.properties['padding'];
    if (padding is EdgeInsets) return padding;
    if (padding is double) return EdgeInsets.all(padding);
    return EdgeInsets.zero;
  }

  Alignment _getAlignment(final LayoutNode node) {
    final alignment = node.properties['alignment'] as String?;
    switch (alignment) {
      case 'center':
        return Alignment.center;
      case 'left':
        return Alignment.centerLeft;
      case 'right':
        return Alignment.centerRight;
      case 'top':
        return Alignment.topCenter;
      case 'bottom':
        return Alignment.bottomCenter;
      default:
        return Alignment.centerLeft;
    }
  }

  TextAlign _getTextAlign(final LayoutNode node) {
    final align = node.properties['alignment'] as String?;
    switch (align) {
      case 'center':
        return TextAlign.center;
      case 'right':
        return TextAlign.right;
      case 'justify':
        return TextAlign.justify;
      default:
        return TextAlign.left;
    }
  }
}
