name: la_design_core
description: uitls for testing
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_staggered_grid_view: ^0.6.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  gap: ^2.0.0
  sliver_tools: ^0.2.5
  flutter_svg: ^1.0.3
  tap_builder: ^0.3.4

dev_dependencies:
  la_test_utils:
    path: ../la_test_utils
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # assets:
  #   - assets/images/
  fonts:
    - family: asgard_icons
      fonts:
        - asset: packages/la_design_core/fonts/asgard_icons.ttf
    - family: Poppins
      fonts:
        - asset: packages/la_design_core/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: packages/la_design_core/fonts/Poppins-Bold.ttf
          weight: 700
