name: core_server_client
description: Starting point for a Serverpod client.

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: ">=3.24.2"

dependencies:
  core:
    path: ../core
  serverpod_auth_client: ^2.1.3
  serverpod_client: ^2.1.3
  shared_models:
    path: ../shared_models

dependency_overrides:
  connectivity_plus: ^6.0.5
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1
  lints: ^5.0.0
  http: ^1.2.2
  uuid: ^4.5.1
