name: core_server_client
description: Starting point for a Serverpod client.

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: ">=3.24.2"

dependencies:
  core:
    path: ../core
  serverpod_auth_client: 1.2.5
  serverpod_client: 1.2.5
  shared_models:
    path: ../shared_models

dependency_overrides:
  connectivity_plus: ^5.0.2
  flutter_lints: ^3.0.0
  google_fonts: ^6.1.0
  lints: ^3.0.0
  http: ^1.1.2
  uuid: ^4.2.1
