name: core_server_client
description: Starting point for a Serverpod client.

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  core:
  serverpod_auth_client: 2.3.1
  serverpod_client: 2.3.1
  shared_models:
