name: core_server_client
description: Starting point for a Serverpod client.

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  core:
  serverpod_auth_client: ^2.3.1
  serverpod_client: ^2.3.1
  shared_models:

dependency_overrides:
  connectivity_plus: ^6.1.2
  lints: ^5.1.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  uuid: ^4.5.1
