name: core_server_client
description: Starting point for a Serverpod client.

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  core:
    path: ../core
  serverpod_auth_client: ^1.1.0
  serverpod_client: 1.1.1

dependency_overrides:
  connectivity_plus: ^5.0.2
  flutter_lints: ^3.0.0
  google_fonts: ^6.1.0
  lints: ^3.0.0
  http: ^1.1.2
  uuid: ^4.2.1
