name: last-answer
version: 1.0.3+9
summary: Fast ideas brainstroming tool
description: |
  You have a cool idea. 
  You need to write it down fast.

  Then this app is for you.

  Follow questions, write as many answers as you can.

  As a result you will get quick description of idea.

  That's it!:)

  Also you can became a super ninja if you use techniques as 'Five whys', 'PDSA', 'Six Sigma'.

  Have an ideas, improvements or bugs? Want to join development?
  [Join Discord](https://discord.gg/y54DpJwmAn) or send a message to idea@xsoulspace.dev.

  Hope this app will be useful for you!
  Thank you and have a nice day.

  You can support development of this app by [buying a cup of cofee](https://www.buymeacoffee.com/arenukvern) or [giving a star its GitHub repository](https://github.com/xsoulspace/last_answer) :)

icon: snap/gui/last-answer.png

confinement: strict
base: core18
grade: stable

slots:
  dbus-last-answer:
    interface: dbus
    bus: session
    name: dev.xsoulspace.lastanswer # adjust accordingly

apps:
  last-answer:
    command: lastanswer
    extensions: [flutter-dev] # Where "master" defines which Flutter channel to use for the build
    # using dev as it is the one channel that supports linux
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
    slots:
      - dbus-last-answer
parts:
  last-answer:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
