name: last-answer
version: 3.19.3+45
summary: Fast ideas brainstorming tool with quick notes
description: |
  Do you have a cool idea and need to get it down quickly? Or do you blog / write articles on social media?

  Then this app is for you.

  In "ideas" answer the questions, write as many answers as you can to get a brief description of the idea and an understanding of how to implement it.
  In "notes" write posts and articles.

  That's all ! :)

  FEATURES

  "Notes" - for bloggers and those who like to write in social networks:

  - Write a note by adding a character limit for the chosen social network.
  - Share it on social networks or messengers.

  "Ideas" - for developers and anyone with ideas to do something new:

  - start with an idea topic, pick questions and answers and share it.
    P.s.: you can become a super ninja if you use techniques such as Five Why's, PDSA, Six Sigma.

  - Messanger style writing - from down to up, the same way as you write in any messanger - just try it and you will like it:)
  - Auto sorting - all projects just feels like "chats" in messanger, so what you write recent - is what you will see as first:)

  NEW & EXPERIMENTAL

  - Folders - now you can organize your ideas and notes in folders.
  - Backup & Restore - now you can backup and restore data from/to files or from/to clipboard. You control your data.

  EXTRA FEATURES

  - Unique & Custom app layout - primary goal is to achive most convenient writing & note orginizing experience.
  - Responsive layout - nice to you if you use it on full screen or in a small window.
  - Dark & Light themes
  - English, Italian, Russian languages

  I hope you find the application useful :)
  Have a nice day!
  ---

  ## Support Development

  You can support this app development by giving a star its GitHub repository - https://github.com/xsoulspace/last_answer 
  Thank you for your support!

icon: snap/gui/last-answer.png
# new template - https://snapcraft.io/docs/flutter-applications
confinement: strict
# https://snapcraft.io/docs/base-snaps
base: core22
grade: stable

slots:
  dbus-last-answer:
    interface: dbus
    bus: session
    name: dev.xsoulspace.lastanswer # adjust accordingly

apps:
  last-answer:
    command: lastanswer
    # snap22 not yet supported by flutter extension,
    # only via plugin (see below)
    # https://snapcraft.io/docs/flutter-extension
    extensions: [gnome] # Where "master" defines which Flutter channel to use for the build
    # using dev as it is the one channel that supports linux
    # extensions: [gnome]
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
    slots:
      - dbus-last-answer

# https://forum.snapcraft.io/t/failed-to-install-or-refresh-a-snap-flutter-does-not-exist/25623
architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  last-answer:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
