name: last-answer
version: 3.5.4+7
summary: Fast ideas brainstroming tool
description: |
  !Please notice: 

  New version now is available at stable channel.
  If you need to use old version, you can switch to beta channel. 
  It will keep old version as long, as all features from previous version will be implemented.
  For implemented features see [roadmap in GitHub](https://github.com/xsoulspace/last_answer/issues/40) 

  ---

  !Please notice:

  New version has no reverse compatibility with old version, 
  so if you decided to use old version - save all data first.

  ---

  You have a cool idea.
  You need to write it down fast.

  Then this app is for you.

  Follow questions, write as many answers as you can.

  As a result, you will get a quick description of the idea.

  That's it!:)

  Also, you can become a super ninja if you use techniques as 'Five whys', 'PDSA', 'Six Sigma'.

  Hope this app will be useful for you :)
  Thank you and have a nice day.

  ---

  ## Have an idea, improvements, or bugs? Want to join development?

  [Join Discord](https://discord.gg/y54DpJwmAn) or send a message to idea@xsoulspace.dev.

  ---

  ## Support Development

  You can support this app development by [giving a star its GitHub repository](https://github.com/xsoulspace/last_answer).
  Thank you for your support!

icon: snap/gui/last-answer.png

confinement: strict
base: core18
grade: stable

slots:
  dbus-last-answer:
    interface: dbus
    bus: session
    name: dev.xsoulspace.lastanswer # adjust accordingly

apps:
  last-answer:
    command: lastanswer
    extensions: [flutter-dev] # Where "master" defines which Flutter channel to use for the build
    # using dev as it is the one channel that supports linux
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
    slots:
      - dbus-last-answer
parts:
  last-answer:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
