name: shared_models
description: Unified data layer & tools
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.5.0
  murmur3: ^2.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  path_to_regexp: ^0.4.0
  quiver: ^3.2.2
  serverpod_client: 2.3.1
  universal_io: ^2.2.2
  uuid: ^4.5.1

dev_dependencies:
  analyzer: ^7.2.0
  build_runner: ^2.4.14
  faker: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  lints: ^5.1.1
  mocktail_image_network: ^1.2.0
  xsoulspace_lints: ^0.0.13
# For information see the following page:
# https://pub.dev/packages/flutter_gen
# flutter_gen:
#   output: lib/src/generated/ # Optional (default: lib/gen/)
#   lineLength: 80
#   assets:
#     enabled: false
#     outputs:
#       gen_for_package: true
#       package_parameter_enabled: true
#   integrations:
#     flutter_svg: false
#   fonts:
#     enabled: false
flutter:
  generate: true
