name: Windows Build
on:
  push:
    branches:
      - master-windows
jobs:
  build:
    name: Build windows
    env:
      my_secret: ${{secrets.COMMIT_SECRET}}
    runs-on: ubuntu-latest
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter build windows
