name: Snapstore Build
on:
  release:
    types: [created]
  push:
    branches:
      - release/snapstore
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: snapcore/action-build@v1
        id: snapcraft
      # Make sure the snap is installable
      - name: Save snap for reuse
        uses: actions/upload-artifact@v4
        with:
          name: last-answer-snap
          path: ${{ steps.snapcraft.outputs.snap }}

  publish:
    # if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download snap
        uses: actions/download-artifact@v3
        with:
          name: last-answer-snap
          path: .
      - name: Publish to Snapstore Edge
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_LOGIN }}
        with:
          snap: ./last-answer.snap
          release: edge
